baseurl = "/"
languageCode = "en-US"
title = "Shavi Hewage"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "fix.GIF"
  author = "Shavi Hewage"
  description = "It's my world and I'm the protagonist"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Instagram     = "sh.avi"
  Facebook      = "shavihewage"
  Email         = "shavihewage@utexas.edu"
  LinkedIn      = "shavihewage"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
