---
title: Using R and Python Together
author: Shavi Hewage
date: '2019-12-13'
slug: heck
categories: []
tags: []
description: ''
---

Have you ever had the urge to do things in two languages at the same time? It's literally code-switching. When you're at home and you're talking to your mom or maybe your grandma, and you unwittingly switch between your home language and English?

**Your mom**: තේ බොමු ද?  
**You**: Sure! Do we have any කිඹුල් බනිස්?  
  
(maybe this is not a *universal* experience, but it is a common experience for a good chunk of people. I learned about code-switching in an intro to anthropology class.)
  
Anyway, kind of like that-- you're at home, you're doing something in R, and you think to yourself, "hey. What if instead of doing everything in one perfectly good language, I throw in some garbage from another? I love making my own life hard! Maybe I'll have to install a package!"  
  
Lucky for you, we can use R and Python together in R studio. What a world, right?  
  
Okay, so imagine you're... doing some kind of homework. And the only problem on this homework is to get the reticulate package to work. So you load the reticulate package. And then you make a funny thing because you're extremely cool and hilarious that way.  

```{r}
library(reticulate)
something<-"This Is"
```
  
You also have to put some python thing in to prove that the reticulate package works. Here you are with the comedy again. But look at that, you print it out and it's a fun little sentence!  

```{python}
dumb="Really Cool"
print(r.something,dumb)
```
You kind of wish you could do something cooler but you couldn't figure out how to import python packages. You're hopeless.
